name: 'JUnit summary'
description: 'Render a job summary from a JUnit test result file'
inputs:
  path:
    description: Path to junit.xml
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
